use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default, Debug)]
pub enum Language {
    #[default]
    PlainText,
    Rust,
    Cpp,
    C,
    CSharp,
    Java,
    JavaScript,
    TypeScript,
    Html,
    Css,
    Json,
    Xml,
    Yaml,
    Markdown,
    Python,
    Sql,
    Shell,
    Go,
    Php,
    Ruby,
}

impl Language {
    pub const ALL: [Language; 20] = [
        Language::PlainText,
        Language::Rust,
        Language::Cpp,
        Language::C,
        Language::CSharp,
        Language::Java,
        Language::JavaScript,
        Language::TypeScript,
        Language::Html,
        Language::Css,
        Language::Json,
        Language::Xml,
        Language::Yaml,
        Language::Markdown,
        Language::Python,
        Language::Sql,
        Language::Shell,
        Language::Go,
        Language::Php,
        Language::Ruby,
    ];

    pub fn from_path(ext: &str) -> Self {
        match ext.to_ascii_lowercase().as_str() {
            "rs" => Language::Rust,
            "cpp" | "cxx" | "cc" | "hpp" => Language::Cpp,
            "c" | "h" => Language::C,
            "cs" => Language::CSharp,
            "java" => Language::Java,
            "js" | "mjs" | "cjs" => Language::JavaScript,
            "ts" | "tsx" => Language::TypeScript,
            "html" | "htm" => Language::Html,
            "css" => Language::Css,
            "json" => Language::Json,
            "xml" => Language::Xml,
            "yaml" | "yml" => Language::Yaml,
            "md" | "markdown" => Language::Markdown,
            "py" => Language::Python,
            "sql" => Language::Sql,
            "sh" | "bash" | "zsh" | "ps1" => Language::Shell,
            "go" => Language::Go,
            "php" => Language::Php,
            "rb" => Language::Ruby,
            _ => Language::PlainText,
        }
    }

    pub fn label(self) -> &'static str {
        match self {
            Language::PlainText => "Plain Text",
            Language::Rust => "Rust",
            Language::Cpp => "C++",
            Language::C => "C",
            Language::CSharp => "C#",
            Language::Java => "Java",
            Language::JavaScript => "JavaScript",
            Language::TypeScript => "TypeScript",
            Language::Html => "HTML",
            Language::Css => "CSS",
            Language::Json => "JSON",
            Language::Xml => "XML",
            Language::Yaml => "YAML",
            Language::Markdown => "Markdown",
            Language::Python => "Python",
            Language::Sql => "SQL",
            Language::Shell => "Shell",
            Language::Go => "Go",
            Language::Php => "PHP",
            Language::Ruby => "Ruby",
        }
    }

    pub fn syntect_name(self) -> &'static str {
        match self {
            Language::PlainText => "txt",
            Language::Rust => "rs",
            Language::Cpp => "cpp",
            Language::C => "c",
            Language::CSharp => "cs",
            Language::Java => "java",
            Language::JavaScript => "js",
            Language::TypeScript => "ts",
            Language::Html => "html",
            Language::Css => "css",
            Language::Json => "json",
            Language::Xml => "xml",
            Language::Yaml => "yaml",
            Language::Markdown => "md",
            Language::Python => "py",
            Language::Sql => "sql",
            Language::Shell => "sh",
            Language::Go => "go",
            Language::Php => "php",
            Language::Ruby => "rb",
        }
    }

    /// Keyword list used by the simple built-in autocomplete engine.
    pub fn keywords(self) -> &'static [&'static str] {
        match self {
            Language::Rust => &[
                "fn", "let", "mut", "struct", "enum", "impl", "trait", "pub", "use", "mod",
                "match", "if", "else", "while", "loop", "for", "in", "return", "self", "Self",
                "true", "false", "None", "Some", "Ok", "Err", "const", "static", "async", "await",
            ],
            Language::Python => &[
                "def", "class", "import", "from", "return", "if", "elif", "else", "while", "for",
                "in", "True", "False", "None", "try", "except", "finally", "with", "as", "lambda",
                "yield", "pass", "break", "continue",
            ],
            Language::JavaScript | Language::TypeScript => &[
                "function",
                "const",
                "let",
                "var",
                "return",
                "if",
                "else",
                "while",
                "for",
                "in",
                "of",
                "class",
                "extends",
                "import",
                "export",
                "default",
                "true",
                "false",
                "null",
                "undefined",
                "async",
                "await",
                "try",
                "catch",
                "finally",
            ],
            Language::Cpp | Language::C => &[
                "int",
                "float",
                "double",
                "char",
                "void",
                "struct",
                "class",
                "public",
                "private",
                "protected",
                "return",
                "if",
                "else",
                "while",
                "for",
                "switch",
                "case",
                "break",
                "continue",
                "const",
                "static",
                "include",
                "namespace",
                "template",
            ],
            Language::Html => &[
                "html",
                "head",
                "body",
                "title",
                "meta",
                "link",
                "script",
                "style",
                "div",
                "span",
                "a",
                "p",
                "ul",
                "ol",
                "li",
                "table",
                "thead",
                "tbody",
                "tr",
                "td",
                "th",
                "form",
                "input",
                "button",
                "label",
                "select",
                "option",
                "textarea",
                "img",
                "video",
                "audio",
                "source",
                "iframe",
                "header",
                "footer",
                "nav",
                "main",
                "section",
                "article",
                "aside",
                "h1",
                "h2",
                "h3",
                "h4",
                "h5",
                "h6",
                "br",
                "hr",
                "strong",
                "em",
                "b",
                "i",
                "u",
                "code",
                "pre",
                "blockquote",
                "figure",
                "figcaption",
                "canvas",
                "svg",
                "template",
                "class",
                "id",
                "href",
                "src",
                "alt",
                "type",
                "value",
                "name",
                "placeholder",
                "target",
                "rel",
                "disabled",
                "checked",
                "required",
                "onclick",
                "DOCTYPE",
            ],
            Language::Xml => &[
                "xml",
                "version",
                "encoding",
                "standalone",
                "xmlns",
                "DOCTYPE",
                "CDATA",
            ],
            Language::Json => &["true", "false", "null"],
            Language::Css => &[
                "color",
                "background",
                "background-color",
                "margin",
                "padding",
                "border",
                "border-radius",
                "display",
                "flex",
                "flex-direction",
                "justify-content",
                "align-items",
                "position",
                "absolute",
                "relative",
                "fixed",
                "static",
                "sticky",
                "width",
                "height",
                "min-width",
                "max-width",
                "font-size",
                "font-family",
                "font-weight",
                "text-align",
                "overflow",
                "z-index",
                "opacity",
                "transition",
                "transform",
                "grid",
                "grid-template-columns",
                "box-shadow",
                "cursor",
                "visibility",
                "float",
                "clear",
                "line-height",
                "content",
            ],
            _ => &[],
        }
    }
}
